SECRET_KEY=your_secret_key
FLASK_APP=flask_for_startups.py
FLASK_DEBUG=1
FLASK_CONFIG=dev
DEV_DATABASE_URI=postgresql://your_user:your_password@localhost/flask_for_startups
TEST_DATABASE_URI=postgresql://your_user:your_password@localhost/test_flask_for_startups
REMEMBER_COOKIE_HTTPONLY=True
SESSION_COOKIE_SAMESITE=Lax
